version: 3.8build{build}
clone_depth: 5
branches:
  only:
    - 3.4
cache:
  - externals -> PCbuild
before_build:
  - ps: |+
      Exit-AppveyorBuild

environment:
  HOST_PYTHON: C:\Python36\python.exe
image:
  - Visual Studio 2017
