version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "skip issue"
      - "skip news"
  - package-ecosystem: "pip"
    directory: "/Tools/clinic/"
    schedule:
      interval: "monthly"
    labels:
      - "skip issue"
      - "skip news"
