version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "skip issue"
      - "skip news"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/Tools/"
    schedule:
      interval: "monthly"
    labels:
      - "skip issue"
      - "skip news"
