codecov:
  notify:
    require_ci_to_pass: true
comment: off
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: off
    project: off
    patch:
      default:
        target: 75%
        only_pulls: true
        paths:
          - Lib/**/*
        threshold: 0.01
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
