select = [
    "F811",
]
extend-exclude = [
    # Failed to lint
    "Lib/test/badsyntax_pep3120.py",
    "Lib/test/encoded_modules/module_iso_8859_1.py",
    "Lib/test/encoded_modules/module_koi8_r.py",
    # Failed to parse
    "Lib/test/mod_generics_cache.py",
    "Lib/test/badsyntax_3131.py",
    "Lib/test/support/socket_helper.py",
    "Lib/test/test_builtin.py",
    "Lib/test/test_fstring.py",
    "Lib/test/test_funcattrs.py",
    "Lib/test/test_functools.py",
    "Lib/test/test_type_aliases.py",
    "Lib/test/test_type_params.py",
    "Lib/test/test_typing.py",
    # TODO Fix: F811 Redefinition of unused name
    "Lib/test/test__opcode.py",
    "Lib/test/test_buffer.py",
    "Lib/test/test_ctypes/test_arrays.py",
    "Lib/test/test_ctypes/test_functions.py",
    "Lib/test/test_dataclasses/__init__.py",
    "Lib/test/test_descr.py",
    "Lib/test/test_enum.py",
    "Lib/test/test_genericclass.py",
    "Lib/test/test_grammar.py",
    "Lib/test/test_import/__init__.py",
    "Lib/test/test_keywordonlyarg.py",
    "Lib/test/test_pkg.py",
    "Lib/test/test_subclassinit.py",
    "Lib/test/test_unittest/testmock/testpatch.py",
    "Lib/test/test_yield_from.py",
    "Lib/test/time_hashlib.py",
]
