# Current docs for the syntax of this file are at:
#  https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted.md

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

queue:
  name: Hosted Linux Preview

trigger:
- master
- 3.7
- 3.6
- vsts

#variables:

steps:
- checkout: self
  clean: true
  fetchDepth: 5

- task: UsePythonVersion@0
  displayName: 'Use Python 3.6 or later'
  inputs:
    versionSpec: '>=3.6'

- script: apt-get install texlive-full
  displayName: 'Install LaTeX'

- script: python -m pip install sphinx blurb python-docs-theme
  displayName: 'Install build dependencies'

- script: make dist PYTHON=python SPHINXBUILD='python -m sphinx' BLURB='python -m blurb'
  workingDirectory: '$(build.sourcesDirectory)/Doc'
  displayName: 'Build documentation'

- task: PublishBuildArtifacts@1
  displayName: 'Publish generated Docs'
  inputs:
    PathToPublish: '$(build.sourcesDirectory)/Doc/build'
    ArtifactName: build
    publishLocation: Container
