# Current docs for the syntax of this file are at:
#  https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted.md

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

queue:
  name: Hosted Linux Preview

trigger:
- master
- vsts

#variables:

steps:
- checkout: self
  clean: true
  fetchDepth: 5

- script: deb-src http://archive.ubuntu.com/ubuntu/ xenial main && sudo apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install libssl-dev
  displayName: 'Install build dependencies'

- script: ./configure --with-pydebug
  displayName: 'Configure CPython (debug)'

- script: make -s -j4
  displayName: 'Build CPython'

- script: make pythoninfo
  displayName: 'Display build info'

# - script: make buildbottest TESTOPTS="-j4 -uall,-cpu,-network"
#   displayName: 'Tests'
