# Current docs for the syntax of this file are at:
#  https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted.md

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

queue:
  name: Hosted Linux Preview

trigger:
  branches:
    include:
    - master
    - 3.7
    - 3.6
    - vsts
  paths:
    exclude:
    - Doc/*
    - Tools/*

variables:
  # Copy-pasted from linux-deps.yml until template support arrives
  OPENSSL: 1.1.0g
  OPENSSL_DIR: "$HOME/multissl/openssl/$(OPENSSL)"
  PATH: "$(OPENSSL_DIR)/bin:$(PATH)"
  # Use -O3 because we don't use debugger on Travis-CI
  CFLAGS: "-I$(OPENSSL_DIR)/include -O3"
  LDFLAGS: "-L$(OPENSSL_DIR)/lib"
  # Set rpath with env var instead of -Wl,-rpath linker flag
  # OpenSSL ignores LDFLAGS when linking bin/openssl
  LD_RUN_PATH: "$(OPENSSL_DIR)/lib"

steps:
- checkout: self
  clean: true
  fetchDepth: 5

#- template: linux-deps.yml

# See https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-templates.md
# For now, we copy/paste the steps
- script: echo "deb-src http://archive.ubuntu.com/ubuntu/ xenial main" > /etc/apt/sources.list.d/python.list && sudo apt-get update
  displayName: 'Update apt-get lists'

- script: sudo apt-get -yq build-dep python3.5
- script: sudo apt-get -yq install uuid-dev
- script: python Tools/ssl/multissltests.py --steps=library --base-directory $HOME/multissl --openssl $(OPENSSL) >/dev/null 2>&1


- script: ./configure --with-pydebug
  displayName: 'Configure CPython (debug)'

- script: make -s -j4
  displayName: 'Build CPython'

- script: ./python -m venv venv && ./venv/bin/python -m pip install -U coverage
  displayName: 'Set up virtual environment'

- script: ./venv/bin/python -m test.pythoninfo
  displayName: 'Display build info'

- script: ./venv/bin/python -m coverage run --pylib -m test --fail-env-changed -uall,-cpu -x test_multiprocessing_fork -x test_multiprocessing_forkserver -x test_multiprocessing_spawn -x test_concurrent_futures
  displayName: 'Tests with coverage'

- script: source ./venv/bin/activate && bash <(curl -s https://codecov.io/bash)
  displayName: 'Publish code coverage results'
