name: Bug report
description: Submit a bug report
labels: ["type-bug"]
body:
  - type: markdown
    attributes:
      value: |
        **New to Python?**

        For help or advice on using Python, try one of the following options instead of opening a GitHub issue:

          - Posting on [Discourse](https://discuss.python.org/c/users/7)
          - Reading the [Python tutorial](https://docs.python.org/3/tutorial/)
          - Emailing [python-list](https://mail.python.org/mailman/listinfo/python-list)

        Also make sure to search the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc) to check that the bug has not already been reported.
  - type: textarea
    attributes:
      label: "Bug description:"
      description: >
        Give a clear and concise description of what happened.
        Include a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) if possible.
        Copy and paste code where possible rather than using screenshots,
        and put any code blocks inside triple backticks.

      value: |
        ```python
        # Add a code block here, if required
        ```
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "CPython versions tested on:"
      multiple: true
      options:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "CPython main branch"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Operating systems tested on:"
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: false
