contact_links:
  - about: "Ask questions about using Python and debugging errors on Discourse."
    name: "Getting help"
    url: "https://discuss.python.org/c/users/7"
  - about: "Submit major feature proposal (e.g. syntax changes) to an ideas forum first."
    name: "Proposing new features"
    url: "https://discuss.python.org/c/ideas/6"
  - about: "See here for details on reporting security vulnerabilities in CPython"
    name: "Reporting security vulnerabilities"
    url: "https://www.python.org/dev/security/"
