target-version = "py312"
line-length = 79
fix = true

[format]
quote-style = "single"

[lint]
select = [
    "ALL",
    "TCH",
]
ignore = [
    # isort
    'I001', # unsorted or unformatted import
    # mccabbe
    "C901",
    # pydocstyle
    "D",
    # flake8-quotes (Q)
    'Q000', # double quotes found but single quotes preferred
    'Q001', # single quote docstring found but double quotes preferred
    # flake8-print (T20)
    'T201', # print found
    # pylint (PL)
    'PLR0912', # too many branches
    'PLR2004', # avoid magic values
]

[lint.isort]
required-imports = ["from __future__ import annotations"]

[lint.pycodestyle]
max-doc-length = 79
