name: CPython_Build_Test

on:
  #push:
  #  branches:
  #  - master
  #  - 3.8
  #  - 3.7
  #  paths-ignore:
  #  - 'Doc/**'
  #  - 'Misc/**'
  pull_request:
    branches:
    - master
    - 3.8
    - 3.7
    paths-ignore:
    - 'Doc/**'
    - 'Misc/**'

jobs:
  build_win32:
    name: 'Windows (x86)'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build CPython
      run: .\PCbuild\build.bat -e -p Win32
    - name: Display build info
      run: .\python.bat -m test.pythoninfo
    - name: Tests
      run: .\PCbuild\rt.bat -q -uall -u-cpu -rwW --slowest --timeout=1200 -j0

  build_win_amd64:
    name: 'Windows (x64)'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build CPython
      run: .\PCbuild\build.bat -e -p x64
    - name: Display build info
      run: .\python.bat -m test.pythoninfo
    - name: Tests
      run: .\PCbuild\rt.bat -x64 -q -uall -u-cpu -rwW --slowest --timeout=1200 -j0

  build_macos:
    name: 'macOS'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure CPython
      run: ./configure --with-pydebug --with-openssl=/usr/local/opt/openssl --prefix=/opt/python-dev
    - name: Build CPython
      run: make -s -j4
    - name: Display build info
      run: make pythoninfo
    - name: Tests
      run: make buildbottest TESTOPTS="-j4 -uall,-cpu"

  build_ubuntu:
    name: 'Ubuntu'
    runs-on: ubuntu-latest
    env:
      OPENSSL_VER: 1.1.1d
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: sudo ./.github/workflows/posix-deps-apt.sh
    - name: 'Restore OpenSSL build'
      id: cache-openssl
      uses: actions/cache@v1
      with:
        path: ./multissl/${{ env.OPENSSL_VER }}
        key: ${{ runner.os }}-multissl-${{ env.OPENSSL_VER }}
    - name: Install OpenSSL
      if: steps.cache-openssl.outputs.cache-hit != 'true'
      run: python3 Tools/ssl/multissltests.py --steps=library --base-directory $PWD/multissl --openssl $OPENSSL_VER --system Linux
    - name: Configure CPython
      run: ./configure --with-pydebug --with-openssl=$PWD/multissl/openssl/$OPENSSL_VER
    - name: Build CPython
      run: make -s -j4
    - name: Display build info
      run: make pythoninfo
    - name: Tests
      run: xvfb-run make buildbottest TESTOPTS="-j4 -uall,-cpu"

  build_ubuntu_coverage:
    name: 'Ubuntu (Coverage)'
    runs-on: ubuntu-latest
    env:
      OPENSSL_VER: 1.1.1d
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: sudo ./.github/workflows/posix-deps-apt.sh
    - name: 'Restore OpenSSL build'
      id: cache-openssl
      uses: actions/cache@v1
      with:
        path: ./multissl/${{ env.OPENSSL_VER }}
        key: ${{ runner.os }}-multissl-${{ env.OPENSSL_VER }}
    - name: Install OpenSSL
      if: steps.cache-openssl.outputs.cache-hit != 'true'
      run: python3 Tools/ssl/multissltests.py --steps=library --base-directory $PWD/multissl --openssl $OPENSSL_VER --system Linux
    - name: Configure CPython
      run: ./configure --with-pydebug --with-openssl=$PWD/multissl/openssl/$OPENSSL_VER
    - name: Build CPython
      run: make -s -j4
    - name: Display build info
      run: make pythoninfo
    - name: 'Coverage Preparation'
      run: |
        ./python -m venv venv
        source ./venv/bin/activate
        python -m pip install -U coverage
        python -m test.pythoninfo
    - name: 'Tests with coverage'
      run: >
        source ./venv/bin/activate
        xvfb-run ./venv/bin/python -m coverage run --pylib
        -m test
        --fail-env-changed
        -uall,-cpu
        -x test_multiprocessing_fork
        -x test_multiprocessing_forkserver
        -x test_multiprocessing_spawn
        -x test_concurrent_futures
    - name: 'Publish code coverage results'
      run: |
        source ./venv/bin/activate
        python -m coverage xml
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
