name: Tests

# gh-84728: "paths-ignore" is not used to skip documentation-only PRs, because
# it prevents to mark a job as mandatory. A PR cannot be merged if a job is
# mandatory but not scheduled because of "paths-ignore".
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - '3.*'
  pull_request:
    branches:
    - 'main'
    - '3.*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-reusable
  cancel-in-progress: true

jobs:
  build_windows:
    name: 'Windows'
    uses: ./.github/workflows/reusable-windows.yml

  build_windows_free_threading:
    name: 'Windows (free-threading)'
    uses: ./.github/workflows/reusable-windows.yml
    with:
      free-threading: true
