name: JIT

on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  jit:
    name: JIT / ${{ matrix.debug && 'Debug' || 'Release' }} / LLVM ${{ matrix.llvm }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        debug: [false, true]
        llvm: [14, 15, 16]
        os: [macOS, Ubuntu, Windows]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ matrix.llvm }}
      - if: matrix.os != 'Windows' && matrix.debug
        run: ./configure --with-pydebug
      - if: matrix.os != 'Windows' && !matrix.debug
        run: ./configure
      - if: matrix.os != 'Windows'
        run: make all --jobs
      - if: matrix.os == 'Windows' && matrix.debug
        run: ./PCbuild/build.bat -d
      - if: matrix.os == 'Windows' && !matrix.debug
        run: ./PCbuild/build.bat
      - if: matrix.os == 'macOS'
        run: ./python.exe -m test --multiprocess 0
      - if: matrix.os == 'Ubuntu'
        run: ./python -m test --multiprocess 0
      - if: matrix.os == 'Windows'
        run: ./python.bat -m test --multiprocess 0
