name: JIT
on: push
permissions:
  contents: read
jobs:
  jit:
    name: ${{ matrix.target }}${{ matrix.debug_flag }} (LLVM ${{ matrix.llvm }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        debug:
          - false
          - true
        llvm:
          - 14
          - 15
          - 16
        target:
          - i686-pc-windows-msvc/msvc
          - x86_64-pc-windows-msvc/msvc
          - x86_64-apple-darwin/clang
          - x86_64-unknown-linux-gnu/gcc
          # - aarch64-apple-darwin/clang
          # - aarch64-unknown-linux-gnu/gcc
          # - aarch64-unknown-linux-gnu/clang
          # - powerpc64le-unknown-linux-gnu/gcc
          - x86_64-unknown-linux-gnu/clang
        include:
          - target: i686-pc-windows-msvc/msvc
            runner: windows-latest
            tier: 1
            platform: Win32
          - target: x86_64-pc-windows-msvc/msvc
            runner: windows-latest
            tier: 1
            platform: x64
          - target: x86_64-apple-darwin/clang
            runner: macos-latest
            tier: 1
          - target: x86_64-unknown-linux-gnu/gcc
            runner: ubuntu-latest
            tier: 1
            compiler: gcc
          # - target: aarch64-apple-darwin/clang
          #   runner: macos-latest
          #   tier: 2
          #   compiler: clang
          # - target: aarch64-unknown-linux-gnu/gcc
          #   runner: ubuntu-latest
          #   tier: 2
          #   compiler: gcc
          # - target: aarch64-unknown-linux-gnu/clang
          #   runner: ubuntu-latest
          #   tier: 2
          #   compiler: clang
          # - target: powerpc64le-unknown-linux-gnu/gcc
          #   runner: ubuntu-latest
          #   tier: 2
          #   compiler: gcc
          - target: x86_64-unknown-linux-gnu/clang
            runner: ubuntu-latest
            tier: 2
            compiler: clang
          - debug: true
            runner: windows-latest
            debug_flag: ' -d'
          - debug: true
            debug_flag: ' --with-pydebug'
          - debug_flag: ''
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run (macOS)
        if: matrix.runner == 'macos-latest'
        run: |
          brew install llvm@${{ matrix.llvm }}
          export SDKROOT="$(xcrun --show-sdk-path)"
          ./configure${{ matrix.debug_flag }}
          make all
          ./python.exe -c 'import sys; assert sys._support_tier == ${{ matrix.tier }}, sys._support_tier'
          ./python.exe -m test -j0 -wW
      - name: Run (Ubuntu)
        if: matrix.runner == 'ubuntu-latest'
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" ./llvm.sh ${{ matrix.llvm }}
          export CC="${{ matrix.compiler }}"
          ./configure${{ matrix.debug_flag }}
          make all
          ./python -c 'import sys; assert sys._support_tier == ${{ matrix.tier }}, sys._support_tier'
          ./python -m test -j0 -wW
      - name: Run (Windows)
        if: matrix.runner == 'windows-latest'
        run: |
          choco install llvm --version ${{ matrix.llvm }}
          ./PCbuild/build${{ matrix.debug_flag }} -p ${{ matrix.platform }}
          ./python -c 'import sys; assert sys._support_tier == ${{ matrix.tier }}, sys._support_tier'
          ./PCbuild/rt${{ matrix.debug_flag }} -p ${{ matrix.platform }} -q -j0 -wW
