# Workflow to run mypy on select parts of the CPython repo
name: mypy

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "Lib/test/libregrtest/**"
      - "Tools/clinic/**"
      - "Tools/cases_generator/**"
      - "Tools/peg_generator/**"
      - "Tools/requirements-dev.txt"
      - ".github/workflows/mypy.yml"
  workflow_dispatch:

permissions:
  contents: read

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  FORCE_COLOR: 1
  TERM: xterm-256color  # needed for FORCE_COLOR to work on mypy on Ubuntu, see https://github.com/python/mypy/issues/13817

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  mypy:
    strategy:
      matrix:
        target: [
          "Lib/test/libregrtest",
          "Tools/cases_generator",
          "Tools/clinic",
          "Tools/peg_generator",
        ]
    name: Run mypy on ${{ matrix.target }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: Tools/requirements-dev.txt
      - run: pip install -r Tools/requirements-dev.txt
      - if: ${{ matrix.target != 'Lib/test/libregrtest' }}
        run: mypy --config-file ${{ matrix.target }}/mypy.ini
      - if: ${{ matrix.target == 'Lib/test/libregrtest' }}
        # Mypy can't be run on libregrtest from the repo root,
        # or it (amusingly) thinks that the entire Lib directory is "shadowing the stdlib",
        # and refuses to do any type-checking at all
        run: |
          cd Lib/test
          mypy --config-file libregrtest/mypy.ini
