name: Check labels

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

permissions:
  issues: read
  pull-requests: read

jobs:
  label:
    name: DO-NOT-MERGE / unresolved review
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: mheap/github-action-required-labels@422e4c352ef83db91089e6acfbf09d8725e08abc  # v4
        with:
          mode: exactly
          count: 0
          labels: "DO-NOT-MERGE, awaiting changes, awaiting change review"
