name: Check labels

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

permissions:
  issues: read
  pull-requests: read

jobs:
  label:
    name: DO-NOT-MERGE / unresolved review
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: mheap/github-action-required-labels@4e9ef4ce8c697cf55716ecbf7f13a3d9e0b6ac6a # v5.1.0
        with:
          mode: exactly
          count: 0
          labels: "DO-NOT-MERGE, awaiting changes, awaiting change review"
