on:
  workflow_call:
    inputs:
      config_hash:
        required: true
        type: string

jobs:
  build_wasi_reusable:
    name: 'build and test'
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    env:
      WASI_SDK_VERSION: 20
      WASI_SDK_PATH: /opt/wasi-sdk
      WASMTIME_VERSION: 18.0.2
    steps:
    - uses: actions/checkout@v4
    # No problem resolver registered as one doesn't currently exist for Clang.
    - name: "Install wasmtime"
      uses: jcbhmr/setup-wasmtime@v2
      with:
        wasmtime-version: ${{ env.WASMTIME_VERSION }}
    - name: "Restore WASI SDK"
      id: cache-wasi-sdk
      uses: actions/cache@v4
      with:
        path: ${{ env.WASI_SDK_PATH }}
        key: ${{ runner.os }}-wasi-sdk-${{ env.WASI_SDK_VERSION }}
    - name: "Install WASI SDK"
      if: steps.cache-wasi-sdk.outputs.cache-hit != 'true'
      run: |
        mkdir ${{ env.WASI_SDK_PATH }} && \
        curl -s -S --location https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${{ env.WASI_SDK_VERSION }}/wasi-sdk-${{ env.WASI_SDK_VERSION }}.0-linux.tar.gz | \
        tar --strip-components 1 --directory ${{ env.WASI_SDK_PATH }} --extract --gunzip
    # XXX ccache
    # XXX restore config.cache for build
    # XXX restore config.cache for wasi
    - name: "Install Python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: "Configure build Python"
      run: python3 Tools/wasm/wasi.py configure-build-python -- -C --with-pydebug
    - name: "Make build Python"
      run: python3 Tools/wasm/wasi.py make-build-python
    - name: "Configure host"
      run: python3 Tools/wasm/wasi.py configure-host
    - name: "Make host"
      run: python3 Tools/wasm/wasi.py make-host
    - name: Display build info
      run: make --directory cross-build/wasm32-wasi pythoninfo
    - name: "Test"
      run: make --directory cross-build/wasm32-wasi test
