name: Reusable Windows

on:
  workflow_call:
    inputs:
      os:
        description: OS to run on
        required: true
        type: string
      arch:
        description: CPU architecture
        required: true
        type: string
      free-threading:
        description: Whether to compile CPython in free-threading mode
        required: false
        type: boolean
        default: false

env:
  FORCE_COLOR: 1
  IncludeUwp: >-
    true

jobs:
  build:
    name: ${{ inputs.arch == 'arm64' && 'build' || 'build and test' }} (${{ inputs.arch }})
    runs-on: ${{ inputs.os }}
    timeout-minutes: 60
    env:
      ARCH: ${{ inputs.arch }}
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Register MSVC problem matcher
      if: inputs.arch != 'Win32'
      run: echo "::add-matcher::.github/problem-matchers/msvc.json"
    - name: Build CPython
      run: >-
        .\\PCbuild\\build.bat
        -e -d -v
        -p "${ARCH}"
        ${{ fromJSON(inputs.free-threading) && '--disable-gil' || '' }}
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: windows-${{ inputs.arch }}${{ fromJSON(inputs.free-threading) && '-t' || '' }}-bin
        path: ./PCbuild/${{ inputs.arch }}
    - name: Display build info
      run: .\\python.bat -m test.pythoninfo
      shell: cmd
    - name: Tests
      run: >-
        .\\PCbuild\\rt.bat
        -p "${ARCH}"
        -d -q --fast-ci
        ${{ fromJSON(inputs.free-threading) && '--disable-gil' || '' }}
      shell: bash
