name: Verify bundled wheels

on:
  workflow_dispatch:
  push:
    paths:
      - 'Lib/ensurepip/_bundled/**'
      - '.github/workflows/verify-ensurepip-wheels.yml'
      - 'Tools/build/verify_ensurepip_wheels.py'
  pull_request:
    paths:
      - 'Lib/ensurepip/_bundled/**'
      - '.github/workflows/verify-ensurepip-wheels.yml'
      - 'Tools/build/verify_ensurepip_wheels.py'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435  # v4.5.0
        with:
          python-version: '3'
      - name: Compare checksum of bundled wheels to the ones published on PyPI
        run: ./Tools/build/verify_ensurepip_wheels.py
