name: Verify bundled pip and setuptools

on:
  workflow_dispatch:
  push:
    paths:
      - 'Lib/ensurepip/_bundled/**'
  pull_request:
    paths:
      - 'Lib/ensurepip/_bundled/**'

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compare checksums of bundled pip and setuptools to ones published on PyPI
        run: ./Misc/verify-bundled-wheels.sh
